a <-read.csv("rts.csv")
View(a)
class(a) 
iu=ts(a$instruments.usage,start = min(a$period),end = max(a$period),frequency = 1)
class(iu)
library(forecast)
library(tseries)
plot(iu)
acf(iu)
pacf(iu)
adf.test(iu)
t=auto.arima(iu,ic="aic",trace = TRUE)
acf(ts(t$residuals))
pacf(ts(t$residuals))
myforecast=forecast(t,level = c(95),h=10*1)
myforecast
plot(myforecast)
Box.test(myforecast$resid, lag=5, type= "Ljung-Box")
Box.test(myforecast$resid, lag=15, type= "Ljung-Box")
Box.test(myforecast$resid, lag=25, type= "Ljung-Box")
